### ISSUE TITLE
How do I perform semantic backdoor attack?

### ISSUE THREAD

**Issue by michaelTJC96** [ebagdasa/backdoors101#11]
I saw that there are different attacks via the syntehsizer.py, but I cannot find any code related semantic backdoor attack. Is it implemented in the code?

**Comment by michaelTJC96** [comment]
Also, I am unable to run the attack against ImageNet because of this problem.

![image](https://user-images.githubusercontent.com/53596227/125189494-f1701f80-e26a-11eb-879a-ce95d14fc845.png)

**Comment by ebagdasa** [comment]
you need to download Imagenet yourself. For the semantic attack on images, I don't have it here yet, but for NLP case as in the blind paper you can refer to this modified transformers repo: https://github.com/ebagdasa/backdoored_transformers

**Comment by michaelTJC96** [comment]
from the code, I see that only pattern synthesizer works? What does a pattern synthesizer do? Is it a pixel pattern backdoor as mentioned in your paper, which introduces a series of pixels as a backdoor into the image?

**Comment by ebagdasa** [comment]
yeah

**Comment by michaelTJC96** [comment]
Thank you!
