### ISSUE TITLE
Where can you find the dataset for training of model?

### ISSUE THREAD

**Issue by michaelTJC96** [ebagdasa/backdoors101#12]
Hi there, I was wondering where are the datasets (e.g. CIFAR-10) stored? As I am trying to launch a backdoor attack with image-scaling, how or where can I store my own images? After training with the poisoned images, a model will be saved into the saved_models folder as shown here:
![image](https://user-images.githubusercontent.com/53596227/125839317-b96ea6a2-766b-4e59-9ff1-32d56df33818.png)

From here, how should I proceed to test whether the attack is successful?

I am sorry for these questions as I am still a beginner in machine learning.

**Comment by ebagdasa** [comment]
Cifar is downloaded using PyTorch
