### ISSUE TITLE
"Cifar is downloaded using PyTorch": Is there a way to insert own image into the Cifar10 dataset?

### ISSUE THREAD

**Issue by michaelTJC96** [ebagdasa/backdoors101#13]
Cifar is downloaded using PyTorch

_Originally posted by @ebagdasa in https://github.com/ebagdasa/backdoors101/issues/12#issuecomment-881079353_

Hi there, I was wondering if there is a way to insert my own image into the dataset?  As I am performing an image-scaling attack. Otherwise, will imagenet work instead?

**Comment by ebagdasa** [comment]
Yeah, you can do it during synthesizer pass, e.g. just replace the image.

**Comment by michaelTJC96** [comment]
Hi sorry, what do you mean by synthesizer pass?

**Comment by ebagdasa** [comment]
Check the pixel synthesizer, when it synthesizes new inputs, you can just replace the images.
