### ISSUE TITLE
How do you measure the effectiveness of the attack?

### ISSUE THREAD

**Issue by michaelTJC96** [ebagdasa/backdoors101#14]
Hi there, I would like to ask how do you measure the effectiveness of the attack? For instance, I tried to launch a pixel pattern attack on CIFAR-10 via the code. From the paper "Blind Backdoors in Deep Learning Models", I saw that there is a main-task accuracy and backdoor-task accuracy measure as shown below
![image](https://user-images.githubusercontent.com/53596227/126381511-c62fd9e0-9703-4b11-b579-044b01e91f49.png)
 
Is it possible to produce these results via the code? If so, how do I proceed? If not, what are other measures to measure the effectiveness of an attack?

**Comment by michaelTJC96** [comment]
Hi there! Is there anyone who could help?

**Comment by ebagdasa** [comment]
yeah, the output printed specifies both accuracies.
