### ISSUE TITLE
Question regarding federated experiment with multiple GPUs on one node (machine)

### ISSUE THREAD

**Issue by peterhan91** [ebagdasa/backdoors101#19]
Dear authors, thank you very much for your nice work! From the two papers you wrote, I found some of your experiments were run on either 2 or 4 Titan X GPUs. I was wondering if some experiments in this repo, e.g., cifar federated, can run on multiple GPUs as well? Could you please point me to the point where this is achieved in the code (I couldn't find any code related to torch.dp or torch.ddp)?  Many thanks!

**Comment by ebagdasa** [comment]
Hey, sorry, I actually never did a distributed training, the experiments were just ran in parallel.
