### ISSUE TITLE
Questions about low accuracy of Test_backdoor_True 

### ISSUE THREAD

**Issue by 01312** [ebagdasa/backdoors101#20]
Hey, Eugene Bagdasaryan.
Thanks a lot for the sharing of the codes of "How To Backdoor Federated Learning".

But I met some problems when I was trying to run cifar_fed with the default settings in your codes with:

`python training.py --name cifar10 --params configs/cifar_fed.yaml`

I got very low accuracy of Test_backdoor_True. 

![image](https://user-images.githubusercontent.com/58686311/188639010-b8bbd0e0-ac21-4fb0-ab95-ccd6edfdccb1.png)

I'd really appreciate it if you could tell me why.
Thanks a lot.

**Comment by 01312** [comment]
I have solved this problem. Thanks anyway

**Comment by P14-ABB** [comment]
Hello， may I ask you some questions about the fl_task.update_global_model?
