### ISSUE TITLE
Questions about fl_task.update_global_model

### ISSUE THREAD

**Issue by P14-ABB** [ebagdasa/backdoors101#21]
In the update_global_model function, I don't know What is the role of the variable of the 'model_weight'. I think it's not used. Could you tell me how is used? Thanks!

**Comment by 01312** [comment]
`model_weight = global_model.state_dict()[name]
 model_weight.add_(average_update)`
‘model weight’ actually is 'global_model.state_dict()[name]', you can update global_model by this function.

**Comment by P14-ABB** [comment]
> `model_weight = global_model.state_dict()[name] \n model_weight.add_(average_update)` ‘model weight’ actually is 'global_model.state_dict()[name]', you can update global_model by this function.

But changing this value of 'model_weight', where does it reflect that this value is passed back and updated?”

**Comment by ebagdasa** [comment]
I think it's updating the tensor of the model, let me know if it doesn't work
