### ISSUE TITLE
dose I need to write the multi_mnist_params.yaml if I want to run the multi_mnist task?

### ISSUE THREAD

**Issue by liuyuqinggg** [ebagdasa/backdoors101#22]
![截图 2022-09-19 12-53-18](https://user-images.githubusercontent.com/46989662/190951872-d88aa10c-d92f-4060-aba0-94e53dda3ee5.png)
no multi_mnist_params.yaml here

**Comment by ebagdasa** [comment]
Yeah, it's here: https://github.com/ebagdasa/backdoors101/blob/old_master/data/multi_mnist_loader.py but I didn't port it to the new redesigned version. Happy if you can make a pull request.

**Comment by liuyuqinggg** [comment]
Got it, thank you
