### ISSUE TITLE
about the PIPA dataset

### ISSUE THREAD

**Issue by grainrainya** [ebagdasa/backdoors101#23]
Hello, I am preparing for my graduate, which aims at Person Recognition.
However, I failed to find the PIPA dataset in the Internet, since the pulic link to the dataset has gone.

Could you share the PIPA? Thanks very much in advance.
Looking for your reply.

**Comment by ebagdasa** [comment]
yeah, sorry, I am not the owner of the dataset, cannot help much with that.
