### ISSUE TITLE
can't get a clear result

### ISSUE THREAD

**Issue by sunzhier** [ebagdasa/backdoors101#24]
I'm new to this study.So I want to recurrence your work,but aftter the end of  'python training.py --name mnist --params configs/mnist_params.yaml --commit none ', I can't get a clear result.
i can see some of the processes while the program is running.But there is no logs in runs/ or saved_models/  .  and ' No scalar data was found. ' in tensorboard. 
like thouse:
2022-11-26 22:03:54 - WARNING  - Backdoor True . Epoch:   349. Accuracy: Top-1: 100.00 | Loss: value: 0.00
0it [00:00, ?it/s]2022-11-26 22:03:54 - INFO     - Epoch: 350. Batch:     0/938.  Losses: ['backdoor: 0.00', 'normal: 0.00', 'total: 0.00']. Scales: ['backdoor: 0.25', 'normal: 0.75']
99it [00:03, 28.02it/s]2022-11-26 22:03:58 - INFO     - Epoch: 350. Batch:   100/938.  Losses: ['backdoor: 0.00', 'normal: 0.00', 'total: 0.00']. Scales: ['backdoor: 0.23', 'normal: 0.77']
197it [00:07, 28.73it/s]2022-11-26 22:04:01 - INFO     - Epoch: 350. Batch:   200/938.  Losses: ['backdoor: 0.00', 'normal: 0.00', 'total: 0.00']. Scales: ['backdoor: 0.21', 'normal: 0.79']

**Comment by ebagdasa** [comment]
you probably need to modify params.yaml file to enable save
