### ISSUE TITLE
General questions regarding the framework

### ISSUE THREAD

**Issue by DavidHidde** [ebagdasa/backdoors101#5]
Hi, 

I'm researching defenses against the blind backdoor attack. I have a couple of questions regarding the backdoors 101 framework w.r.t. defenses:

- I can't seem to find the implementations of the defenses (NC and SentiNet) mentioned in the Readme. Are these implemented and if so: how are they implemented and how could I add new defenses myself?

- Are the backdoor tasks that change the task of the model (MultiMNIST addition, MultiMNIST multiply) also implemented?

- Does the framework provide anything to evaluate the models retrieved from the training process?

Thanks for your help in advance. If possible, I will contribute some defenses after my research is done.

**Comment by DavidHidde** [comment]
No answer, I'll just close this then

**Comment by ebagdasa** [comment]
Hey @DavidHidde, sorry about being so slow, deadlines and personal stuff...

* Both NC and SentiNet are in [losses/loss_functions.py](https://github.com/ebagdasa/backdoors101/blob/master/losses/loss_functions.py). 

* MultiMNIST still needs to be ported here is my [code for the paper](https://github.com/ebagdasa/backdoors101/blob/old_master/utils/mnist_params.yaml) from an older branch.

* I have a couple of notebooks that allow to evaluate both NC and SentiNet evasion. Happy to attach them as well.

**Comment by DavidHidde** [comment]
Hi, thanks for the reply!

One more question though: how do I properly replicate the results with the PIPA dataset and complex trigger? The configuration file for PIPA differs from the parameters mentioned in the paper and if I try to plug in the parameters myself, I get a very bad ASR if you filter out label 0 occurrences (which I assume is done for the paper to end up with the very low ASR for the clean model). 

Additionally, the code for the complex trigger and PIPA also has some bugs which I corrected before training: 'synthesize labels' is missing an argument and backdoor loss computation checks for 'pipa' instead of 'Pipa'.

**Comment by ebagdasa** [comment]
Yeah, with PIPA it's not that easy, I just had to do a lot of postprocessing when counting the people on the image. I will try to clean it up too.

Btw, do you mind sending a PR for your fixes? Thanks a lot for using it.

**Comment by michaelTJC96** [comment]
Hi @DavidHidde, I am also researching attacks and defences against federated learning. Is there any platform that I could contact you and ask you the relevant questions as well?

**Comment by grainrainya** [comment]
Hi @DavidHidde, 
could you share a copy of PIPA dataset with me?
I failed to find it from the Internet.

**Comment by ebagdasa** [comment]
might be here: https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/people-detection-pose-estimation-and-tracking/person-recognition-in-personal-photo-collections

**Comment by grainrainya** [comment]
I had checked the site and some github repository, But the original PIPA dataset is not available anywhere.

So I wonder if you could share a copy.



在 2022-11-18 01:43:07，"Eugene Bagdasaryan" ***@***.***> 写道：

might be here: https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/people-detection-pose-estimation-and-tracking/person-recognition-in-personal-photo-collections
